import React from 'react';
import { BRAND } from '../config/brand';
import { AlertTriangle, ShieldCheck, Scale, Globe, Info } from 'lucide-react';
import PageSeo from '../components/common/PageSeo';

export default function Disclaimer() {
  return (
    <div className="container py-5" style={{ maxWidth: '840px' }}>
      <PageSeo
        title="Disclaimer – Website SEO & Marketing Tools"
        description="Read the official disclaimer for SEO++. Understand our automated SEO audit limitations, trademark disclosures, and accuracy statements."
        canonicalUrl="https://seoplusplus.vercel.app/disclaimer"
        breadcrumbs={[
          { name: 'Home', url: '/' },
          { name: 'Disclaimer', url: '/disclaimer' }
        ]}
      />

      <div className="mb-5 text-center">
        <div className="brand-icon mx-auto mb-3" aria-hidden="true">
          <AlertTriangle size={22} />
        </div>
        <h1 className="h2 fw-bold text-main mb-2">Disclaimer</h1>
        <p className="text-muted small">Last updated: October 2026</p>
      </div>

      <div className="p-4 p-md-5 rounded-4 border d-flex flex-column gap-4" style={{ backgroundColor: 'var(--bg-card)' }}>
        <p className="text-secondary mb-0">
          The information, automated audit scores, keyword suggestions, metrics, and content generation utilities provided on <strong>{BRAND.name}</strong> (accessible at <a href="https://seoplusplus.vercel.app/" className="text-primary text-decoration-none">https://seoplusplus.vercel.app/</a>) are published strictly for informational, educational, and creative purposes.
        </p>

        {/* 1. Automated SEO Audit & Scoring Limitations */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2 d-flex align-items-center gap-2">
            <Scale size={18} className="text-primary" />
            <span>1. Automated SEO Audit &amp; Scoring Limitations</span>
          </h2>
          <p className="text-secondary small mb-2">
            The health score and technical recommendations generated by our <strong>SEO Checker</strong> are determined by programmatic heuristics evaluating the publicly accessible HTML, HTTP headers, and metadata of the submitted webpage at the time of the crawl:
          </p>
          <ul className="text-secondary small mb-2 ps-3">
            <li><strong>No Ranking Guarantee:</strong> A high score on SEO++ does not guarantee top positions on Google, Bing, Yahoo, or any search engine. Conversely, a lower score does not necessarily mean your webpage cannot rank.</li>
            <li><strong>Algorithm Independence:</strong> Search engine ranking algorithms (including Google's core updates, helpful content systems, and neural ranking models) evaluate hundreds of dynamic, proprietary factors, including brand signals, user interaction, backlink quality, and domain history that cannot be measured via single-page static HTML inspection.</li>
            <li><strong>Point-in-Time Assessment:</strong> Network latency, firewalls, bot detection layers (e.g. Cloudflare, AWS WAF), and dynamic JavaScript rendering can influence crawl results.</li>
          </ul>
        </div>

        {/* 2. Client-Side Marketing & Social Media Tools */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2 d-flex align-items-center gap-2">
            <Globe size={18} className="text-primary" />
            <span>2. Generated Copy, Captions, Hooks &amp; Ideas</span>
          </h2>
          <p className="text-secondary small mb-0">
            Our Hashtag Generator, Caption Generator, Hook Generator, and Content Ideas tools generate suggestions based on deterministic, rule-based algorithms and curated templates. Users are solely responsible for verifying the accuracy, appropriateness, tone, factual claims, and copyright compliance of any generated copy before publishing it on social platforms or digital properties.
          </p>
        </div>

        {/* 3. Third-Party Trademarks & Independence */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2 d-flex align-items-center gap-2">
            <ShieldCheck size={18} className="text-primary" />
            <span>3. Third-Party Trademarks &amp; Non-Affiliation</span>
          </h2>
          <p className="text-secondary small mb-2">
            All product names, trademarks, logos, and brands mentioned on {BRAND.name} are the property of their respective owners:
          </p>
          <ul className="text-secondary small mb-2 ps-3">
            <li><strong>Google &amp; Google Search Console:</strong> Google, Google Search Console, and Google Ads are registered trademarks of Google LLC. {BRAND.name} is an independent utility and is not affiliated with, authorized, maintained, sponsored, or endorsed by Google LLC.</li>
            <li><strong>Ahrefs &amp; Domain Rating:</strong> Ahrefs and Domain Rating (DR) are trademarks or service marks of Ahrefs Pte. Ltd. {BRAND.name} accesses public data points solely for user reporting and is not endorsed by Ahrefs.</li>
            <li><strong>Social Media Platforms:</strong> Instagram, TikTok, LinkedIn, YouTube, Facebook, and X (formerly Twitter) are trademarks of their respective owners. Mention of these platforms does not imply any affiliation or endorsement.</li>
          </ul>
        </div>

        {/* 4. Advertising & Sponsored Disclosures */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2 d-flex align-items-center gap-2">
            <Info size={18} className="text-primary" />
            <span>4. Advertising &amp; Commercial Disclosures</span>
          </h2>
          <p className="text-secondary small mb-0">
            To keep our tools 100% free for everyone, {BRAND.name} may display digital advertising from third-party advertising networks (such as Google AdSense). Advertisements are clearly distinguished from editorial tools and recommendations. Any sponsored articles in our publication are explicitly tagged as "Sponsored Content" in accordance with Google guidelines and international advertising standards.
          </p>
        </div>

        {/* 5. Professional Advice Disclaimer */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">5. Professional Advice Disclaimer</h2>
          <p className="text-secondary small mb-0">
            The tools and articles on {BRAND.name} do not constitute professional legal, financial, architectural, or enterprise technical consulting. You should consult qualified specialists before making critical business or infrastructure migrations based on automated audit reports.
          </p>
        </div>

        {/* 6. Contact & Corrections */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">6. Contact for Corrections</h2>
          <p className="text-secondary small mb-0">
            If you notice an inaccuracy in any of our technical checklists, documentation, or tool outputs, please contact us via our <a href="/contact" className="text-primary text-decoration-none">Contact page</a> or submit an issue on our GitHub repository.
          </p>
        </div>
      </div>
    </div>
  );
}
