import React from 'react';
import { BRAND } from '../config/brand';
import { FileText, AlertCircle } from 'lucide-react';

export default function Terms() {
  return (
    <div className="container py-5" style={{ maxWidth: '840px' }}>
      <div className="mb-5 text-center">
        <div className="brand-icon mx-auto mb-3" aria-hidden="true">
          <FileText size={22} />
        </div>
        <h1 className="h2 fw-bold text-main mb-2">Terms of Service</h1>
        <p className="text-muted small">Last updated: September 2026</p>
      </div>

      <div className="p-4 p-md-5 rounded-4 border" style={{ backgroundColor: 'var(--bg-card)' }}>
        <p className="text-secondary mb-4">
          Welcome to <strong>{BRAND.name}</strong>. By accessing or using our website, SEO checker, and marketing tools, you agree to these Terms of Service.
        </p>

        {/* 1. Purpose of the Service */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">1. Purpose of the Service</h2>
          <p className="text-secondary small mb-0">
            {BRAND.name} provides free, automated website SEO audits and client-side marketing utilities (including hashtag generation, caption drafting, hook templates, content brainstorming, character counting, and UTM link building) for informational and creative assistance.
          </p>
        </div>

        {/* 2. Responsibilities for Generated Content */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">2. Responsibilities for Generated Content</h2>
          <p className="text-secondary small mb-2">
            All copy, hashtags, opening hooks, and content suggestions generated by our tools are template-based drafts intended to inspire and assist your writing:
          </p>
          <ul className="text-secondary small mb-0 ps-3">
            <li>You are solely responsible for reviewing, editing, and verifying any content before publishing it on social networks or web properties.</li>
            <li>You agree to comply with the community guidelines and terms of service of any third-party platforms (e.g. Instagram, TikTok, LinkedIn, YouTube, Facebook, X) where you publish content or hashtags.</li>
            <li>Do not use generated content for unlawful, deceptive, defamatory, or abusive purposes.</li>
          </ul>
        </div>

        {/* 3. SEO Score & Performance Disclaimers */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">3. SEO Score and Performance Disclaimers</h2>
          <div className="audit-disclaimer-box mb-3 mt-1">
            <AlertCircle size={20} className="text-primary flex-shrink-0" />
            <div className="small text-muted">
              <strong>Explicit Disclaimer:</strong> The SEO score is an automated assessment based on the checks performed by the tool and should not be interpreted as a guarantee of search engine rankings. No tool guarantees reach, viral engagement, follower growth, or conversions.
            </div>
          </div>
          <p className="text-secondary small mb-0">
            Search engine algorithms and social media distribution mechanisms involve dynamic factors outside the scope of automated heuristic checks.
          </p>
        </div>

        {/* 4. Acceptable Use of the SEO Checker */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">4. Acceptable Use of the SEO Checker</h2>
          <p className="text-secondary small mb-0">
            You agree to submit only publicly available URLs that you own, operate, or are authorized to audit. Probing private intranet addresses, loopback endpoints (such as localhost or 127.0.0.1), or engaging in denial of service attempts is strictly prohibited and blocked by our security layers.
          </p>
        </div>

        {/* 5. UTM Builder & Client-Side Execution */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">5. UTM Builder and Client-Side Execution</h2>
          <p className="text-secondary small mb-0">
            Our UTM builder functions exclusively in your web browser. You are responsible for testing and validating tracking links before deploying them in live advertising or email marketing campaigns.
          </p>
        </div>

        {/* 6. Service Availability & Changes */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">6. Service Availability and Changes</h2>
          <p className="text-secondary small mb-0">
            {BRAND.name} is provided on a free, "as-is" and "as-available" basis without warranties of any kind. We reserve the right to modify tools, refine templates, or adjust scoring algorithms at any time without notice.
          </p>
        </div>

        {/* 7. Limitation of Liability */}
        <div className="mb-4">
          <h2 className="h5 fw-bold text-main mb-2">7. Limitation of Liability</h2>
          <p className="text-secondary small mb-0">
            To the maximum extent permitted by law, {BRAND.name} and its contributors shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our tools, reports, or generated copy.
          </p>
        </div>

        {/* 8. Contact Information */}
        <div className="mb-0">
          <h2 className="h5 fw-bold text-main mb-2">8. Contact Information</h2>
          <p className="text-secondary small mb-0">
            For questions regarding these Terms of Service, please reach out through our official community channels and open-source project repository.
          </p>
        </div>
      </div>
    </div>
  );
}
