import React from 'react';
import { BRAND } from '../config/brand';
import { FileText, AlertCircle, Scale, Shield, CheckCircle2 } from 'lucide-react';
import PageSeo from '../components/common/PageSeo';

export default function Terms() {
  return (
    <div className="container py-5" style={{ maxWidth: '840px' }}>
      <PageSeo
        title="Terms of Service – User Agreement"
        description="Review the Terms of Service for SEO++. Understand user responsibilities, acceptable usage rules, intellectual property, and service limitations."
        canonicalUrl="https://seoplusplus.vercel.app/terms"
        breadcrumbs={[
          { name: 'Home', url: '/' },
          { name: 'Terms of Service', url: '/terms' }
        ]}
      />

      <div className="mb-5 text-center">
        <div className="brand-icon mx-auto mb-3" aria-hidden="true">
          <FileText size={22} />
        </div>
        <h1 className="h2 fw-bold text-main mb-2">Terms of Service</h1>
        <p className="text-muted small">Last updated: October 2026</p>
      </div>

      <div className="p-4 p-md-5 rounded-4 border d-flex flex-column gap-4" style={{ backgroundColor: 'var(--bg-card)' }}>
        <p className="text-secondary mb-0">
          Welcome to <strong>{BRAND.name}</strong>. By accessing or using our website, SEO checker, and digital marketing tools, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
        </p>

        {/* 1. Purpose of the Service */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">1. Scope and Purpose of the Platform</h2>
          <p className="text-secondary small mb-0">
            {BRAND.name} provides free automated website SEO audits, Search Console performance visualization, keyword brainstorming, domain metrics, and client-side marketing utilities (including hashtag generation, caption drafting, hook templates, content ideas, character counting, and UTM link building) strictly for informational and creative assistance.
          </p>
        </div>

        {/* 2. Responsibilities for Generated Content */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">2. Responsibilities for Generated Copy &amp; Assets</h2>
          <p className="text-secondary small mb-2">
            All text, opening hooks, hashtag collections, and content outlines generated by our tools are template-based drafts intended to inspire and assist your writing:
          </p>
          <ul className="text-secondary small mb-0 ps-3">
            <li>You are solely responsible for reviewing, editing, fact-checking, and verifying any content before publishing it on social networks or web properties.</li>
            <li>You agree to comply with the community guidelines and terms of service of any third-party platforms (e.g. Instagram, TikTok, LinkedIn, YouTube, Facebook, X) where you share content or hashtags.</li>
            <li>You must not use generated copy for unlawful, deceptive, defamatory, trademark-infringing, or abusive purposes.</li>
          </ul>
        </div>

        {/* 3. SEO Score & Performance Disclaimers */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">3. SEO Score and Ranking Disclaimers</h2>
          <div className="audit-disclaimer-box mb-3 mt-1">
            <AlertCircle size={20} className="text-primary flex-shrink-0" />
            <div className="small text-muted">
              <strong>Explicit Disclaimer:</strong> SEO audit scores represent automated heuristic assessments based on static page signals and do not guarantee search engine rankings, indexing speed, or organic traffic. No tool guarantees reach, engagement, followers, or business conversions.
            </div>
          </div>
          <p className="text-secondary small mb-0">
            Search engine algorithms continuously evolve with dynamic ranking signals beyond the scope of automated static page inspection.
          </p>
        </div>

        {/* 4. Acceptable Use Policy */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">4. Acceptable Use of the SEO Checker &amp; Crawlers</h2>
          <p className="text-secondary small mb-0">
            You agree to submit only publicly accessible URLs that you own, operate, or are explicitly authorized to audit. Probing private intranet addresses, loopback endpoints (such as localhost, 127.0.0.1, or RFC 1918 private subnets), or engaging in denial-of-service attempts against our infrastructure or third-party target hosts is strictly prohibited and actively blocked by our security layers.
          </p>
        </div>

        {/* 5. Google Search Console Integration */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">5. Google Search Console Integration Terms</h2>
          <p className="text-secondary small mb-2">
            When connecting your Google account to view Search Console performance:
          </p>
          <ul className="text-secondary small mb-0 ps-3">
            <li><strong>Authorization &amp; Ownership:</strong> You confirm that you are the verified owner of, or have explicit permission to access, any connected Search Console properties.</li>
            <li><strong>Read-Only Querying:</strong> {BRAND.name} requests strictly read-only access (<code>webmasters.readonly</code>). We do not modify, submit, or delete sitemaps, properties, or settings.</li>
            <li><strong>Third-Party Disclaimer:</strong> {BRAND.name} is an independent utility not affiliated with or endorsed by Google LLC. Service uptime and data delivery are dependent on Google API availability and quotas.</li>
            <li><strong>Disconnecting:</strong> You may disconnect at any time from within the tool interface or revoke access in your Google Account security settings.</li>
          </ul>
        </div>

        {/* 6. Service Availability & Changes */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">6. Service Availability and Changes</h2>
          <p className="text-secondary small mb-0">
            {BRAND.name} is provided on a free, "as-is" and "as-available" basis without warranties of any kind, whether express or implied. We reserve the right to modify, refine, update, or discontinue tools, scoring rules, or templates at any time without notice.
          </p>
        </div>

        {/* 7. Limitation of Liability */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">7. Limitation of Liability</h2>
          <p className="text-secondary small mb-0">
            To the maximum extent permitted by applicable law, {BRAND.name}, its maintainers, and contributors shall not be liable for any direct, indirect, incidental, consequential, or punitive damages resulting from your use of or inability to use our tools, reports, recommendations, or generated content.
          </p>
        </div>

        {/* 8. Contact Information */}
        <div>
          <h2 className="h5 fw-bold text-main mb-2">8. Contact Information</h2>
          <p className="text-secondary small mb-0">
            If you have questions regarding these Terms of Service, please contact us via our <a href="/contact" className="text-primary text-decoration-none">Contact page</a> or through our official <a href="https://github.com/subhan-subi/SEOplusplus" target="_blank" rel="noopener noreferrer" className="text-primary text-decoration-none">GitHub Repository</a>.
          </p>
        </div>
      </div>
    </div>
  );
}
