import { sanitizeFilename, downloadBlob, generateCsv, formatReportDate } from './exportUtils';

/**
 * Exports Domain Rating report as a structured CSV spreadsheet
 *
 * @param {Object} result - Result from checkDomainRating
 * @param {Object} tier - Authority tier metadata from getDrTier
 */
export function exportDrReportCsv(result, tier) {
  const domain = result.domain || result.target || 'domain';
  const { fullStr } = formatReportDate(result.checkedAt);

  const rows = [
    ['SEO++ DOMAIN RATING (DR) AUDIT REPORT'],
    ['Generated by SEO++ (https://seoplusplus.vercel.app/)'],
    ['Scan Date & Time', fullStr],
    [],
    ['TARGET METRICS OVERVIEW'],
    ['Target Domain', domain],
    ['Ahrefs Domain Rating (DR)', `${result.domainRating} / 100`],
    ['Authority Tier', tier?.tier || 'N/A'],
    ['Authority Classification', tier?.label || 'N/A'],
    ['Ahrefs Global Rank (AR)', result.ahrefsRank != null ? `#${Number(result.ahrefsRank).toLocaleString()}` : 'Not available in free endpoint'],
    ['Data Provider', result.source || 'Ahrefs API v3'],
    ['Metric Scale', 'Logarithmic Link Authority (0-100)'],
    ['Authority Description', tier?.description || ''],
    [],
    ['AHREFS DOMAIN RATING REFERENCE SCALE'],
    ['Tier', 'DR Score Range', 'Authority Level', 'Description', 'Current Match'],
    ['Tier 1', '80 - 100', 'Very High Authority', 'Exceptional backlink profile among top global domains.', result.domainRating >= 80 ? 'YES' : 'NO'],
    ['Tier 2', '60 - 79', 'High Authority', 'Strong, established backlink foundation for competitive queries.', (result.domainRating >= 60 && result.domainRating < 80) ? 'YES' : 'NO'],
    ['Tier 3', '40 - 59', 'Moderate Authority', 'Healthy organic backlink profile with steady development.', (result.domainRating >= 40 && result.domainRating < 60) ? 'YES' : 'NO'],
    ['Tier 4', '20 - 39', 'Emerging Authority', 'Developing website actively building initial referring domains.', (result.domainRating >= 20 && result.domainRating < 40) ? 'YES' : 'NO'],
    ['Tier 5', '0 - 19', 'New / Low Domain', 'Fresh domain or minimal discovered referring domains.', result.domainRating < 20 ? 'YES' : 'NO'],
    [],
    ['RECOMMENDED ACTIONS TO IMPROVE DOMAIN RATING'],
    ['Priority', 'Strategy', 'Actionable Recommendation'],
    ['High', 'Editorial Link Building', 'Publish original research, proprietary data studies, or free digital utilities that naturally attract citations and press backlinks.'],
    ['High', 'Competitor Backlink Intersect', 'Analyze competitor referring domains to discover industry directories, podcast appearances, and resource page opportunities.'],
    ['Medium', 'Broken Link Reclamation', 'Identify broken 404 links on high-DR industry resources and reach out with your updated, high-value replacement content.'],
    ['Medium', 'Digital PR & Guest Contributions', 'Contribute authoritative thought leadership and guest tutorials to established niche publications adhering to editorial guidelines.'],
    ['Low', 'Internal Link Architecture', 'Distribute equity from top-linked pages to high-potential target landing pages through strategic context-rich internal links.']
  ];

  const csvText = generateCsv(rows);
  const blob = new Blob([csvText], { type: 'text/csv;charset=utf-8;' });
  const filename = sanitizeFilename(domain, 'dr-report', 'csv');
  downloadBlob(blob, filename);
}

/**
 * Exports Domain Rating report as a high-quality multi-page PDF document
 *
 * @param {Object} result - Result from checkDomainRating
 * @param {Object} tier - Authority tier metadata from getDrTier
 */
export async function exportDrReportPdf(result, tier) {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const domain = result.domain || result.target || 'domain';
  const { fullStr } = formatReportDate(result.checkedAt);

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  // Primary brand palette
  const brandPrimary = [37, 99, 235];    // #2563eb
  const brandDark = [15, 23, 42];        // #0f172a
  const brandMuted = [100, 116, 139];    // #64748b
  const brandGreen = [5, 150, 105];      // #059669
  const borderGray = [226, 232, 240];    // #e2e8f0
  const bgSubtle = [248, 250, 252];      // #f8fafc

  let y = margin;

  // 1. Header Banner with SEO++ Logo & Branding
  doc.setFillColor(...brandPrimary);
  doc.rect(margin, y, 6, 44, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...brandDark);
  doc.text('SEO++', margin + 14, y + 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...brandMuted);
  doc.text('Free SEO, Search Console & Marketing Toolkit', margin + 14, y + 32);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...brandPrimary);
  doc.text('DOMAIN RATING (DR) AUDIT', pageWidth - margin, y + 18, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  doc.text(`Scanned: ${fullStr}`, pageWidth - margin, y + 32, { align: 'right' });

  y += 54;

  // Thin separator rule
  doc.setDrawColor(...borderGray);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 18;

  // 2. Target Domain & Key Stats Card
  doc.setFillColor(...bgSubtle);
  doc.roundedRect(margin, y, contentWidth, 54, 6, 6, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(margin, y, contentWidth, 54, 6, 6, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...brandMuted);
  doc.text('TARGET DOMAIN', margin + 14, y + 18);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...brandDark);
  doc.text(domain, margin + 14, y + 38);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  doc.text(`Data Provider: ${result.source || 'Ahrefs API v3'}  •  Metric: Logarithmic Link Authority (0-100)`, pageWidth - margin - 14, y + 36, { align: 'right' });

  y += 66;

  // 3. Domain Rating Score Box (Side-by-side with Authority Breakdown)
  const colWidth = (contentWidth - 14) / 2;

  // Left Box: Score Gauge & Tier
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, y, colWidth, 110, 6, 6, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(margin, y, colWidth, 110, 6, 6, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...brandMuted);
  doc.text('AHREFS DOMAIN RATING (DR)', margin + 14, y + 20);

  // Big score number
  const tierColor = result.domainRating >= 80 ? brandGreen :
                    result.domainRating >= 60 ? brandPrimary :
                    result.domainRating >= 40 ? [217, 119, 6] :
                    result.domainRating >= 20 ? [139, 92, 246] : [220, 38, 38];

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(36);
  doc.setTextColor(...tierColor);
  doc.text(String(result.domainRating), margin + 14, y + 58);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(...brandMuted);
  doc.text('/ 100', margin + 74, y + 58);

  // Tier Badge
  doc.setFillColor(tierColor[0], tierColor[1], tierColor[2]);
  doc.roundedRect(margin + 14, y + 72, colWidth - 28, 24, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(tier?.label || 'Authority Score', margin + colWidth / 2, y + 87, { align: 'center' });

  // Right Box: Authority Profile Details
  const rightX = margin + colWidth + 14;
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(rightX, y, colWidth, 110, 6, 6, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(rightX, y, colWidth, 110, 6, 6, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...brandMuted);
  doc.text('AUTHORITY PROFILE SUMMARY', rightX + 14, y + 20);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...brandDark);
  doc.text(tier?.tier || 'Authority Tier', rightX + 14, y + 38);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  const splitDesc = doc.splitTextToSize(tier?.description || '', colWidth - 28);
  doc.text(splitDesc, rightX + 14, y + 52);

  // Global rank if available
  if (result.ahrefsRank != null) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...brandDark);
    doc.text(`Ahrefs Global Rank (AR): #${Number(result.ahrefsRank).toLocaleString()}`, rightX + 14, y + 96);
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(...brandMuted);
    doc.text('Global Rank: Not included in free Ahrefs tier', rightX + 14, y + 96);
  }

  y += 124;

  // 4. Authority Tier Scale & Benchmarks Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...brandDark);
  doc.text('Domain Rating Authority Spectrum & Benchmarks', margin, y);
  y += 10;

  const tableBody = [
    [
      'Tier 1: Global Authority',
      '80 - 100',
      'Exceptional backlink profile among top 0.1% websites globally (e.g., wikipedia.org, github.com).',
      result.domainRating >= 80 ? 'CURRENT DOMAIN' : ''
    ],
    [
      'Tier 2: Established Authority',
      '60 - 79',
      'High-authority brand capable of competing for highly competitive industry keywords.',
      (result.domainRating >= 60 && result.domainRating < 80) ? 'CURRENT DOMAIN' : ''
    ],
    [
      'Tier 3: Growing Authority',
      '40 - 59',
      'Healthy organic backlink profile with consistent referring domain growth.',
      (result.domainRating >= 40 && result.domainRating < 60) ? 'CURRENT DOMAIN' : ''
    ],
    [
      'Tier 4: Early Authority',
      '20 - 39',
      'Developing website actively acquiring initial referring domain links.',
      (result.domainRating >= 20 && result.domainRating < 40) ? 'CURRENT DOMAIN' : ''
    ],
    [
      'Tier 5: New or Niche Domain',
      '0 - 19',
      'Fresh domain or minimal discovered referring domains in the search index.',
      result.domainRating < 20 ? 'CURRENT DOMAIN' : ''
    ]
  ];

  autoTable(doc, {
    startY: y,
    head: [['Authority Tier', 'DR Range', 'Profile Description', 'Status']],
    body: tableBody,
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 8,
      cellPadding: 5,
      textColor: brandDark,
      lineColor: borderGray,
      lineWidth: 0.5
    },
    headStyles: {
      fillColor: brandDark,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5
    },
    columnStyles: {
      0: { cellWidth: 120, fontStyle: 'bold' },
      1: { cellWidth: 60, halign: 'center' },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 95, halign: 'center', fontStyle: 'bold' }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 3 && data.cell.raw === 'CURRENT DOMAIN') {
        data.cell.styles.fillColor = [236, 253, 245]; // light green
        data.cell.styles.textColor = brandGreen;
      }
    },
    margin: { left: margin, right: margin }
  });

  y = doc.lastAutoTable.finalY + 18;

  // 5. Actionable Improvement Recommendations Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...brandDark);
  doc.text('Recommended Actions to Grow Domain Rating & Authority', margin, y);
  y += 10;

  const recsBody = [
    [
      'High',
      'Original Research & Data Studies',
      'Publish original industry reports, statistical surveys, or proprietary studies that naturally attract authoritative journalist and blogger citations.'
    ],
    [
      'High',
      'Free Tools & Digital Assets',
      'Develop free, high-utility interactive tools (calculators, generators, directories) that build organic passive backlinks over time.'
    ],
    [
      'Medium',
      'Broken Backlink Reclamation',
      'Discover dead 404 links on established niche resource pages and pitch your updated content as a drop-in replacement.'
    ],
    [
      'Medium',
      'Digital PR & Editorial Outreach',
      'Collaborate on guest columns, podcasts, and expert roundups with recognized industry authorities adhering strictly to Google webmaster guidelines.'
    ],
    [
      'Low',
      'Internal Equity Distribution',
      'Maximize existing link equity by linking from high-authority landing pages to strategic money pages with descriptive anchor text.'
    ]
  ];

  autoTable(doc, {
    startY: y,
    head: [['Priority', 'Growth Strategy', 'Actionable Execution Step']],
    body: recsBody,
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 8,
      cellPadding: 5,
      textColor: brandDark,
      lineColor: borderGray,
      lineWidth: 0.5
    },
    headStyles: {
      fillColor: brandPrimary,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5
    },
    columnStyles: {
      0: { cellWidth: 60, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 140, fontStyle: 'bold' },
      2: { cellWidth: 'auto' }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 0) {
        if (data.cell.raw === 'High') {
          data.cell.styles.textColor = [220, 38, 38];
        } else if (data.cell.raw === 'Medium') {
          data.cell.styles.textColor = [217, 119, 6];
        } else {
          data.cell.styles.textColor = brandGreen;
        }
      }
    },
    margin: { left: margin, right: margin }
  });

  // 6. Running Footer on all pages
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...borderGray);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 30, pageWidth - margin, pageHeight - 30);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...brandMuted);
    doc.text('SEO++ Domain Rating Report  •  https://seoplusplus.vercel.app/  •  Private & Client-Side', margin, pageHeight - 18);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 18, { align: 'right' });
  }

  const filename = sanitizeFilename(domain, 'dr-report', 'pdf');
  doc.save(filename);
}

/**
 * Invokes browser print dialog for DR report
 */
export function printDrReport() {
  if (typeof window !== 'undefined') {
    window.print();
  }
}
