import { sanitizeFilename, downloadBlob, generateCsv, formatReportDate } from './exportUtils';

/**
 * Exports complete SEO audit report as a structured CSV spreadsheet
 *
 * @param {Object} auditData - Audit data object from analyzeWebsite
 */
export function exportSeoReportCsv(auditData) {
  const url = auditData.normalizedUrl || auditData.url || 'website';
  const { fullStr } = formatReportDate(new Date());

  const checks = auditData.checks || [];
  const recs = auditData.recommendations || [];
  const cats = auditData.categories || {};
  const meta = auditData.meta || {};
  const summary = auditData.summary || {};

  const rows = [
    ['SEO++ WEBSITE TECHNICAL & ON-PAGE SEO AUDIT REPORT'],
    ['Generated by SEO++ (https://seoplusplus.vercel.app/)'],
    ['Scan Date & Time', fullStr],
    [],
    ['EXECUTIVE SUMMARY'],
    ['Target URL', auditData.url || url],
    ['Resolved URL', auditData.normalizedUrl || url],
    ['Overall SEO Score', `${auditData.score || 0} / 100`],
    ['Overall Grade', auditData.grade || 'N/A'],
    ['Total Checks Evaluated', summary.total || checks.length],
    ['Passed Checks', summary.passed || 0],
    ['Warnings Found', summary.warnings || 0],
    ['Failed / Errors Found', summary.failed || 0],
    ['Info Checks', summary.info || 0],
    [],
    ['TECHNICAL & CRAWL METRICS'],
    ['Metric', 'Value'],
    ['Server Response Time (TTFB)', `${meta.responseTimeMs || 0} ms`],
    ['HTML Document Size', `${meta.pageSizeKb || 0} KB`],
    ['Estimated Word Count', `~${meta.wordCount || 0} words`],
    ['Total Images Found', meta.totalImages || 0],
    ['Images Missing ALT Attributes', meta.imagesMissingAlt || 0],
    ['H1 Heading Count', meta.h1Count || 0],
    ['Primary H1 Text', meta.h1 || 'None found'],
    ['H2 Heading Count', meta.h2Count || 0],
    ['Canonical URL Tag', meta.canonicalUrl || 'Not specified'],
    ['Open Graph Meta Present', meta.hasOg ? 'Yes' : 'No'],
    ['Twitter Card Meta Present', meta.hasTwitter ? 'Yes' : 'No'],
    [],
    ['CATEGORY BREAKDOWN SCORES'],
    ['Category', 'Score (0-100)', 'Grade', 'Passed Checks', 'Warnings', 'Failed Checks', 'Total Checks'],
    ...Object.values(cats).map((c) => [
      c.label || 'Category',
      c.score || 0,
      c.grade || 'N/A',
      c.passed || 0,
      c.warnings || 0,
      c.failed || 0,
      c.total || 0
    ]),
    [],
    ['PRIORITIZED ACTION ITEMS'],
    ['Priority Rank', 'Issue Title', 'Category', 'Severity Level', 'Status', 'Recommended Action', 'Why It Matters'],
    ...recs.map((r, i) => [
      `#${i + 1}`,
      r.title || 'Recommendation',
      r.category || 'General',
      r.severity ? r.severity.toUpperCase() : 'MEDIUM',
      r.status ? r.status.toUpperCase() : 'WARNING',
      r.recommendation || '',
      r.whyItMatters || ''
    ]),
    [],
    ['COMPLETE DETAILED AUDIT CHECKS'],
    ['Check ID', 'Category', 'Audit Check Title', 'Status', 'Severity', 'Description / Why It Matters', 'Recommended Fix', 'Sample Details'],
    ...checks.map((c) => {
      let sampleStr = '';
      if (c.details?.sampleMissing && Array.isArray(c.details.sampleMissing)) {
        sampleStr = c.details.sampleMissing.join('; ');
      }
      return [
        c.id || '',
        c.category || '',
        c.title || '',
        c.status ? c.status.toUpperCase() : 'INFO',
        c.severity ? c.severity.toUpperCase() : 'LOW',
        c.description || '',
        c.recommendation || '',
        sampleStr
      ];
    })
  ];

  const csvText = generateCsv(rows);
  const blob = new Blob([csvText], { type: 'text/csv;charset=utf-8;' });
  const filename = sanitizeFilename(url, 'seo-audit', 'csv');
  downloadBlob(blob, filename);
}

/**
 * Exports complete SEO audit report as a high-quality multi-page PDF document
 *
 * @param {Object} auditData - Audit data object from analyzeWebsite
 */
export async function exportSeoReportPdf(auditData) {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const url = auditData.normalizedUrl || auditData.url || 'website';
  const { fullStr } = formatReportDate(new Date());

  const checks = auditData.checks || [];
  const recs = auditData.recommendations || [];
  const cats = auditData.categories || {};
  const meta = auditData.meta || {};
  const summary = auditData.summary || {};

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  // Colors
  const brandPrimary = [37, 99, 235];    // #2563eb
  const brandDark = [15, 23, 42];        // #0f172a
  const brandMuted = [100, 116, 139];    // #64748b
  const brandGreen = [5, 150, 105];      // #059669
  const brandAmber = [217, 119, 6];      // #d97706
  const brandRed = [220, 38, 38];        // #dc2626
  const borderGray = [226, 232, 240];    // #e2e8f0
  const bgSubtle = [248, 250, 252];      // #f8fafc

  let y = margin;

  // 1. Header Banner with SEO++ Logo & Branding
  doc.setFillColor(...brandPrimary);
  doc.rect(margin, y, 6, 44, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...brandDark);
  doc.text('SEO++', margin + 14, y + 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...brandMuted);
  doc.text('Free Website SEO Health & Performance Audit Tool', margin + 14, y + 32);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...brandPrimary);
  doc.text('TECHNICAL & ON-PAGE AUDIT REPORT', pageWidth - margin, y + 18, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  doc.text(`Generated: ${fullStr}`, pageWidth - margin, y + 32, { align: 'right' });

  y += 52;

  // Separator
  doc.setDrawColor(...borderGray);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 14;

  // 2. Target URL Card
  doc.setFillColor(...bgSubtle);
  doc.roundedRect(margin, y, contentWidth, 42, 6, 6, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(margin, y, contentWidth, 42, 6, 6, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  doc.text('TARGET AUDIT URL', margin + 12, y + 16);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...brandDark);
  const truncatedUrl = url.length > 70 ? url.substring(0, 67) + '...' : url;
  doc.text(truncatedUrl, margin + 12, y + 32);

  y += 52;

  // 3. Top Metrics Row: Score Box (Left) + Status Summary (Right)
  const leftColWidth = 160;
  const rightColWidth = contentWidth - leftColWidth - 14;

  // Score Box
  const score = auditData.score || 0;
  const scoreColor = score >= 90 ? brandGreen :
                     score >= 80 ? brandPrimary :
                     score >= 65 ? brandAmber : brandRed;

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, y, leftColWidth, 90, 6, 6, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(margin, y, leftColWidth, 90, 6, 6, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  doc.text('OVERALL SEO SCORE', margin + 12, y + 18);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(34);
  doc.setTextColor(...scoreColor);
  doc.text(String(score), margin + 12, y + 54);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(13);
  doc.setTextColor(...brandMuted);
  doc.text('/ 100', margin + 64, y + 54);

  // Grade badge
  doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.roundedRect(margin + 12, y + 64, leftColWidth - 24, 18, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text(`Grade: ${auditData.grade || 'Evaluated'}`, margin + leftColWidth / 2, y + 76, { align: 'center' });

  // Right Box: Distribution Stats (Passed, Warnings, Errors, Crawl stats)
  const rightX = margin + leftColWidth + 14;
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(rightX, y, rightColWidth, 90, 6, 6, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(rightX, y, rightColWidth, 90, 6, 6, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...brandMuted);
  doc.text('AUDIT CHECKS STATUS DISTRIBUTION', rightX + 12, y + 18);

  // Stat badges
  const statBoxWidth = (rightColWidth - 24 - 16) / 3;

  // Passed
  doc.setFillColor(236, 253, 245);
  doc.roundedRect(rightX + 12, y + 28, statBoxWidth, 48, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...brandGreen);
  doc.text(String(summary.passed || 0), rightX + 12 + statBoxWidth / 2, y + 50, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...brandGreen);
  doc.text('Passed Checks', rightX + 12 + statBoxWidth / 2, y + 66, { align: 'center' });

  // Warnings
  const warnX = rightX + 12 + statBoxWidth + 8;
  doc.setFillColor(255, 251, 235);
  doc.roundedRect(warnX, y + 28, statBoxWidth, 48, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...brandAmber);
  doc.text(String(summary.warnings || 0), warnX + statBoxWidth / 2, y + 50, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...brandAmber);
  doc.text('Warnings', warnX + statBoxWidth / 2, y + 66, { align: 'center' });

  // Failed
  const failX = warnX + statBoxWidth + 8;
  doc.setFillColor(254, 242, 242);
  doc.roundedRect(failX, y + 28, statBoxWidth, 48, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...brandRed);
  doc.text(String(summary.failed || 0), failX + statBoxWidth / 2, y + 50, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...brandRed);
  doc.text('Errors / Failed', failX + statBoxWidth / 2, y + 66, { align: 'center' });

  y += 102;

  // 4. Quick Technical Signals Bar
  doc.setFillColor(...bgSubtle);
  doc.roundedRect(margin, y, contentWidth, 32, 4, 4, 'F');
  doc.setDrawColor(...borderGray);
  doc.roundedRect(margin, y, contentWidth, 32, 4, 4, 'S');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...brandDark);
  const qStats = [
    `TTFB: ${meta.responseTimeMs || 0} ms`,
    `HTML Size: ${meta.pageSizeKb || 0} KB`,
    `Word Count: ~${meta.wordCount || 0}`,
    `Images: ${meta.totalImages || 0} (${meta.imagesMissingAlt || 0} missing ALT)`,
    `H1: ${meta.h1Count || 0}`,
    `H2: ${meta.h2Count || 0}`
  ];
  doc.text(qStats.join('    •    '), margin + 12, y + 20);

  y += 42;

  // 5. Category Breakdown Table with visual scores
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...brandDark);
  doc.text('Category Scores Breakdown', margin, y);
  y += 8;

  const catRows = Object.values(cats).map((c) => [
    c.label || 'Category',
    `${c.score || 0} / 100`,
    c.grade || 'N/A',
    `${c.passed || 0} / ${c.total || 0} checks passed`,
    `${c.warnings || 0} warnings, ${c.failed || 0} failed`
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Score', 'Grade', 'Pass Ratio', 'Issues']],
    body: catRows,
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 8,
      cellPadding: 4,
      textColor: brandDark,
      lineColor: borderGray,
      lineWidth: 0.5
    },
    headStyles: {
      fillColor: brandDark,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5
    },
    columnStyles: {
      0: { cellWidth: 120, fontStyle: 'bold' },
      1: { cellWidth: 70, halign: 'center', fontStyle: 'bold' },
      2: { cellWidth: 80, halign: 'center' },
      3: { cellWidth: 110, halign: 'center' },
      4: { cellWidth: 'auto' }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 1) {
        const num = parseInt(data.cell.raw, 10);
        if (num >= 90) data.cell.styles.textColor = brandGreen;
        else if (num >= 80) data.cell.styles.textColor = brandPrimary;
        else if (num >= 65) data.cell.styles.textColor = brandAmber;
        else data.cell.styles.textColor = brandRed;
      }
    },
    margin: { left: margin, right: margin }
  });

  y = doc.lastAutoTable.finalY + 16;

  // 6. Prioritized Action Items
  if (recs.length > 0) {
    // Check if we need page break
    if (y > pageHeight - 160) {
      doc.addPage();
      y = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...brandDark);
    doc.text(`Prioritized Action Items (${recs.length} Identified Issues)`, margin, y);
    y += 8;

    const recRows = recs.map((r, i) => [
      `#${i + 1}`,
      (r.severity || 'Medium').toUpperCase(),
      r.category || 'SEO',
      r.title || '',
      r.recommendation || ''
    ]);

    autoTable(doc, {
      startY: y,
      head: [['#', 'Priority', 'Category', 'Issue Title', 'Recommended Fix Action']],
      body: recRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7.5,
        cellPadding: 4.5,
        textColor: brandDark,
        lineColor: borderGray,
        lineWidth: 0.5
      },
      headStyles: {
        fillColor: brandPrimary,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8
      },
      columnStyles: {
        0: { cellWidth: 26, halign: 'center', fontStyle: 'bold' },
        1: { cellWidth: 60, halign: 'center', fontStyle: 'bold' },
        2: { cellWidth: 80 },
        3: { cellWidth: 130, fontStyle: 'bold' },
        4: { cellWidth: 'auto' }
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 1) {
          if (data.cell.raw === 'HIGH') {
            data.cell.styles.textColor = brandRed;
            data.cell.styles.fillColor = [254, 242, 242];
          } else if (data.cell.raw === 'MEDIUM') {
            data.cell.styles.textColor = brandAmber;
            data.cell.styles.fillColor = [255, 251, 235];
          } else {
            data.cell.styles.textColor = brandGreen;
          }
        }
      },
      margin: { left: margin, right: margin }
    });

    y = doc.lastAutoTable.finalY + 16;
  }

  // 7. Complete Detailed Audit Checks
  if (checks.length > 0) {
    if (y > pageHeight - 160) {
      doc.addPage();
      y = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...brandDark);
    doc.text(`Detailed Audit Checks & Findings (${checks.length} Total)`, margin, y);
    y += 8;

    const checkRows = checks.map((c) => [
      c.status ? c.status.toUpperCase() : 'INFO',
      c.category || 'General',
      c.title || '',
      c.description || '',
      c.recommendation || ''
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Status', 'Category', 'Check Title', 'Why It Matters', 'How to Fix / Current State']],
      body: checkRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: 4,
        textColor: brandDark,
        lineColor: borderGray,
        lineWidth: 0.5
      },
      headStyles: {
        fillColor: brandDark,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 7.5
      },
      columnStyles: {
        0: { cellWidth: 54, halign: 'center', fontStyle: 'bold' },
        1: { cellWidth: 70 },
        2: { cellWidth: 110, fontStyle: 'bold' },
        3: { cellWidth: 140 },
        4: { cellWidth: 'auto' }
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 0) {
          if (data.cell.raw === 'PASSED') {
            data.cell.styles.textColor = brandGreen;
            data.cell.styles.fillColor = [236, 253, 245];
          } else if (data.cell.raw === 'WARNING') {
            data.cell.styles.textColor = brandAmber;
            data.cell.styles.fillColor = [255, 251, 235];
          } else if (data.cell.raw === 'FAILED') {
            data.cell.styles.textColor = brandRed;
            data.cell.styles.fillColor = [254, 242, 242];
          }
        }
      },
      margin: { left: margin, right: margin }
    });
  }

  // 8. Running Footer with Page Numbers on all pages
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...borderGray);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 30, pageWidth - margin, pageHeight - 30);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...brandMuted);
    doc.text('SEO++ Website SEO Audit Report  •  https://seoplusplus.vercel.app/  •  Private & Client-Side', margin, pageHeight - 18);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 18, { align: 'right' });
  }

  const filename = sanitizeFilename(url, 'seo-audit', 'pdf');
  doc.save(filename);
}

/**
 * Invokes browser print dialog for SEO audit report
 */
export function printSeoReport() {
  if (typeof window !== 'undefined') {
    window.print();
  }
}
